openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https://any.com'
paths:
  /v1/upload:
    post:
      tags:
        - images
      summary: Upload an image
      description: Upload an image
      operationId: Upload an image
      requestBody:
        description: Upload an image
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageRequest'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageResponse'
        '4XX':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '5XX':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

      security:
        - petstore_auth:
            - write:pets
            - read:pets
components:
  schemas:
    ImageRequest:
      type: array
      minItems: 1
      uniqueItems: true
      items:
        $ref: '#/components/schemas/Parts'
    Parts:
      required:
        - part
        - etag
      type: object
      properties:
        part:
          type: integer
          format: int64
          example: 1
        etag:
          type: string
          example: a54357aff0632cce46d942af68356b38
    ImageResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2058959
        timestamp:
          type: integer
          format: int64
          example: 1516354800
        source:
          type: string
          example: instagram
        folder:
          type: string
          example: ~
        height:
          format: int64
          example: 1516354800
        width:
          format: int64
          example: 1516354800
        mime:
          type: string
          example: "image/jpeg"
          "enum": [
            "image/jpeg",
            "image/png",
          ]
        display:
          $ref: '#/components/schemas/Display'
        metadata:
           $ref: '#/components/schemas/Metadata'
    Display:
      type: object
      properties:
        thumbnail:
            $ref: '#/components/schemas/DisplayRecord'
        preview:
          $ref: '#/components/schemas/DisplayRecord'
        square:
          $ref: '#/components/schemas/DisplayRecord'
        original:
          $ref: '#/components/schemas/DisplayRecord'
    DisplayRecord:
      type: object
      properties:
        width:
          format: int64
          example: 1516354800
        height:
          format: int64
          example: 1516354800
        src:
          type: string
          example: https://printu.test/media/catalog/cache/vH72u0x7Y4uf0Tdd1j%252F34EFgAluLOcapxlHI0rcqWYDEZi8ph6XztIsI%252BRE60RFRtAsn/image.jpg
    Metadata:
      type: object
      properties:
        gps:
          type: string
          example: 52/1, 15/1, 272/100 N 21/1, 1/1, 5851/100 E
        datetime:
          type: integer
          example: 1516354800
        name:
          type: string
          example: IMG_9171.JPG
    Error:
      type: object
      properties:
        errorCode:
          type: integer
          format: int64
          example: 400
        userMessage:
          type: string
          example: The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed.
        devMessage:
          type: string
          example: Check the client_id parameter.
        more:
          type: string
          example:
        applicationCode:
          type: string
          example: X1234